language: node_js
node_js:
  - "0.8"
before_install:
  - git submodule update --init
  - npm install -g grunt-cli phantomjs casperjs
  - npm install
  - bower install
before_script:
  - phantomjs --version
script:
  - grunt build test
